# Generated by Django 4.1.7 on 2023-03-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_cuentacobrar_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobrar',
            name='estado',
            field=models.CharField(choices=[('PA', 'Pagado'), ('PE', 'Pediente')], default='PA', max_length=2),
        ),
    ]
