# Generated by Django 4.1.7 on 2023-03-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_cuentacobrar_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacobrar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cliente'),
        ),
        migrations.AlterField(
            model_name='cuentacobrarcuota',
            name='cuenta_cobrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cuentacobrar'),
        ),
        migrations.AlterField(
            model_name='cuentacobrarcuota',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado')], default=0),
        ),
        migrations.AlterField(
            model_name='cuentacobrarpago',
            name='cuenta_cobrar_cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.cuentacobrarcuota'),
        ),
    ]
